import Foundation
import Testing

@testable import FlickrKit

/// Sending a photo to Flickr.
///
/// **The photo is not in the signature; everything else is.** Flickr's upload
/// endpoint takes multipart form data, and the OAuth signature covers every
/// field except the file itself.
@Suite struct UploadRequestTests {

    private let metadata = UploadMetadata(
        title: "Harbour & sea", description: "Piraeus, looking west",
        tags: ["piraeus", "new york"],
        visibility: .init(isPublic: true, isFriend: false, isFamily: false),
        hiddenFromSearch: false)

    private func photoFile(_ bytes: [UInt8] = [0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10],
                           name: String = "harbour.jpg") throws -> URL {
        let folder = FileManager.default.temporaryDirectory
            .appendingPathComponent("caterina-upload-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let file = folder.appendingPathComponent(name)
        try Data(bytes).write(to: file)
        return file
    }

    @Test func theFieldsAreWhatFlickrDocuments() {
        let fields = Dictionary(uniqueKeysWithValues: metadata.parameters.map { ($0.name, $0.value) })
        #expect(fields == ["title": "Harbour & sea", "description": "Piraeus, looking west",
                           "tags": #"piraeus "new york""#,
                           "is_public": "1", "is_friend": "0", "is_family": "0",
                           "hidden": "1", "async": "1"])
    }

    @Test func safetyAndContentTypeAreSentOnlyWhenChosen() {
        let chosen = UploadMetadata(title: "", visibility: .init(isPublic: false, isFriend: true, isFamily: true),
                                    safety: .restricted, contentType: .screenshot, hiddenFromSearch: true)
        let fields = Dictionary(uniqueKeysWithValues: chosen.parameters.map { ($0.name, $0.value) })
        #expect(fields["safety_level"] == "3")
        #expect(fields["content_type"] == "2")
        #expect(fields["hidden"] == "2")
        #expect(fields["title"] == nil)
        let plain = Dictionary(uniqueKeysWithValues: metadata.parameters.map { ($0.name, $0.value) })
        #expect(plain["safety_level"] == nil)
    }

    @Test func theBodyIsWrittenToAFileAndCarriesThePhotoBytesExactly() throws {
        let photo = try photoFile()
        let upload = try UploadRequest.make(file: photo, metadata: metadata,
                                            credentials: Fixtures.credentials,
                                            nonce: "abc", timestamp: 1_700_000_000)
        defer { try? FileManager.default.removeItem(at: upload.body) }

        #expect(upload.request.httpMethod == "POST")
        #expect(upload.request.url?.absoluteString == "https://up.flickr.com/services/upload/")
        let contentType = try #require(upload.request.value(forHTTPHeaderField: "Content-Type"))
        #expect(contentType.hasPrefix("multipart/form-data; boundary="))

        let body = try Data(contentsOf: upload.body)
        let text = String(decoding: body, as: UTF8.self)
        #expect(text.contains(#"Content-Disposition: form-data; name="title""# + "\r\n\r\nHarbour & sea\r\n"))
        #expect(text.contains(#"name="photo"; filename="harbour.jpg""# + "\r\nContent-Type: image/jpeg\r\n\r\n"))
        #expect(body.range(of: Data([0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10])) != nil)
        #expect(text.hasSuffix("--\r\n"))
    }

    /// Generated by `oauthlib` 3.2.2 over the same fields without the photo.
    @Test func theSignatureLeavesThePhotoOut() throws {
        let photo = try photoFile()
        let upload = try UploadRequest.make(file: photo, metadata: metadata,
                                            credentials: Fixtures.credentials,
                                            nonce: "abc", timestamp: 1_700_000_000)
        defer { try? FileManager.default.removeItem(at: upload.body) }
        let text = String(decoding: try Data(contentsOf: upload.body), as: UTF8.self)
        #expect(text.contains("name=\"oauth_signature\"\r\n\r\n04XxASAQQl4sL4W5SVGtTPQmQQA=\r\n"))
    }

    /// A filename is written into a header; a quote or line break in it would
    /// end the header and start another.
    @Test func aFilenameCannotBreakOutOfItsHeader() throws {
        let photo = try photoFile(name: "evil\".jpg")
        let upload = try UploadRequest.make(file: photo, metadata: metadata, credentials: Fixtures.credentials)
        defer { try? FileManager.default.removeItem(at: upload.body) }
        let text = String(decoding: try Data(contentsOf: upload.body), as: UTF8.self)
        #expect(text.contains(#"filename="evil_.jpg""#))
    }

    @Test func aMissingFileSaysWhichFile() {
        let missing = URL(fileURLWithPath: "/nonexistent/harbour.jpg")
        #expect(throws: FlickrError.invalidInput("Could not read harbour.jpg.")) {
            _ = try UploadRequest.make(file: missing, metadata: metadata, credentials: Fixtures.credentials)
        }
    }

    // MARK: - Replies

    @Test func anAsyncUploadAnswersWithATicket() throws {
        let xml = #"<?xml version="1.0" encoding="utf-8" ?><rsp stat="ok"><ticketid>1234-5678</ticketid></rsp>"#
        #expect(try UploadResponse.ticket(from: Data(xml.utf8)) == "1234-5678")
    }

    @Test func aRefusedUploadIsFlickrsError() {
        let xml = #"<rsp stat="fail"><err code="5" msg="Filetype was not recognised" /></rsp>"#
        #expect(throws: FlickrError.api(code: 5, message: "Filetype was not recognised", transient: false)) {
            _ = try UploadResponse.ticket(from: Data(xml.utf8))
        }
    }

    @Test func somethingElseEntirelyIsUnreadable() {
        #expect(throws: FlickrError.self) {
            _ = try UploadResponse.ticket(from: Data("<html>502 Bad Gateway</html>".utf8))
        }
    }

    @Test func ticketsReadAsWhereEachUploadHasGot() throws {
        let json = """
        {"uploader":{"ticket":[{"id":"128","complete":1,"photoid":"2995"},{"id":"129","complete":0},
        {"id":"130","complete":2},{"id":"131","invalid":1}]},"stat":"ok"}
        """
        let statuses = try UploadResponse.tickets(from: Data(json.utf8))
        #expect(statuses == ["128": .done(photoID: "2995"), "129": .processing,
                             "130": .failed, "131": .invalid])
    }
}
