import Foundation
import Testing

@testable import FlickrKit

/// Writing to Flickr: the same OAuth signature, carried in a form body.
///
/// **Every Flickr write method must be POSTed.** A signed GET of
/// `flickr.photos.setMeta` is refused. The signature covers the body's
/// parameters exactly as for a query, so the body must be encoded with the
/// same RFC 5849 encoder — form encoding's `+` for a space would describe a
/// different request than the one signed.
@Suite struct SignedPostTests {

    private let parameters = [
        OAuthParameter(name: "method", value: "flickr.photos.setMeta"),
        OAuthParameter(name: "photo_id", value: "123"),
        OAuthParameter(name: "title", value: "Blue sky & sea"),
        OAuthParameter(name: "description", value: "ünï+code"),
        OAuthParameter(name: "format", value: "json"),
        OAuthParameter(name: "nojsoncallback", value: "1"),
    ]

    private func request() throws -> URLRequest {
        try OAuth1.signedPOSTRequest(url: FlickrClient.endpoint, parameters: parameters,
                                     credentials: Fixtures.credentials,
                                     nonce: "abc", timestamp: 1_700_000_000)
    }

    private func bodyFields(_ request: URLRequest) throws -> [String: String] {
        let body = try #require(request.httpBody.flatMap { String(data: $0, encoding: .utf8) })
        var fields: [String: String] = [:]
        for pair in body.split(separator: "&") {
            let parts = pair.split(separator: "=", maxSplits: 1).map(String.init)
            fields[parts[0].removingPercentEncoding!] = parts[1].removingPercentEncoding!
        }
        return fields
    }

    @Test func itIsAPostWithEverythingInTheBody() throws {
        let request = try request()
        #expect(request.httpMethod == "POST")
        #expect(request.url?.absoluteString == FlickrClient.endpoint)
        #expect(request.url?.query == nil)
        #expect(request.value(forHTTPHeaderField: "Content-Type")
                == "application/x-www-form-urlencoded")
    }

    /// Generated by `oauthlib` 3.2.2 with `SIGNATURE_TYPE_BODY`, not derived
    /// from this implementation.
    @Test func theSignatureMatchesAnIndependentImplementation() throws {
        let fields = try bodyFields(request())
        #expect(fields["oauth_signature"] == "FbJzGL2KDLRmiDT5eeFedyy7/Pw=")
        #expect(fields["title"] == "Blue sky & sea")
        #expect(fields["oauth_token"] == "token")
    }

    @Test func theBodyUsesPercentTwentyNeverPlus() throws {
        let body = try #require(try request().httpBody.flatMap { String(data: $0, encoding: .utf8) })
        #expect(body.contains("title=Blue%20sky%20%26%20sea"))
        #expect(body.contains("description=%C3%BCn%C3%AF%2Bcode"))
        #expect(!body.contains("+"))
    }
}
